<h2>Sign up using this form</h2>

<?php //echo $this->tag->form("playtime/phalcon/tutorial/public/signup/register"); ?>

<form action="http://localhost/playtime/phalcon/tutorial/public/signup/register" method="post">
 <p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name") ?>
 </p>

 <p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField("email") ?>
 </p>

 <p>
    <?php echo $this->tag->submitButton("Register") ?>
 </p>

</form>